### ISSUE TITLE
urltest example

### ISSUE THREAD

**Issue by its0ka** [chika0801/sing-box-examples#106]
i don't get how to use it properly, please give an example

**Comment by chika0801** [comment]
I don't use this feature and can't help you. Suggest you go to sing-box's github for help.

**Comment by its0ka** [comment]
i asked for another example there and dev told me he won't be a teacher and closed the topic for commenting, i then complained for another issue and he banned me

**Comment by chika0801** [comment]
The developers there have always had a similar attitude. I really don't use the feature either, so I haven't looked into it.

Maybe this is the kind of question that when you can't ask anyone else, the only way to try to understand it on the internet is to learn it on your own, and by asking AI.
