### ISSUE TITLE
VMess-WebSocket-TLS疑问？

### ISSUE THREAD

**Issue by tt-2024** [chika0801/sing-box-examples#107]
这种场景下，是否可以把Nginx去掉，直接在sing-box里面配置tls?
目前就是在sing-box里面配置的tls，v2rayN可以连接。但是套上cf cdn 之后就一直报ssl错误。

**Comment by chika0801** [comment]
> 这种场景下，是否可以把Nginx去掉，直接在sing-box里面配置tls?

https://github.com/fscarmen/sing-box 我和这仓库的作者聊时，他说他这样试了，是可以的。建议你去那边咨询他试试看。

> 但是套上cf cdn 之后就一直报ssl错误。

这个我帮不上你，我不用CDN，就不花时间测你说的这形式配置了。
