### ISSUE TITLE
iOS无法使用

### ISSUE THREAD

**Issue by snowmeng696** [chika0801/sing-box-examples#108]
![微信图片_20240323005824](https://github.com/chika0801/sing-box-examples/assets/164542462/68365d23-9cbf-4628-b813-9ed2fa41b147)
为什么会这样啊

**Comment by chika0801** [comment]
下载这个文件失败，根据你的配置，比如这文件一般来说是用代理去下载，然后它失败了，说明你出站proxy部分的配置，你要么客户端哪些参数没写对，没和服务端的对应上，不通，所以这文件就下载失败了。
