### ISSUE TITLE
配置

### ISSUE THREAD

**Issue by onefoxjump** [chika0801/sing-box-examples#109]
使用tun中的[config_client_windows_local_dns.json]存在DNS泄露，如何在该配置示例的基础上最小化修改来避免呢？

**Comment by chika0801** [comment]
文件标题写的就是是本地dns，

你如果不了解dns规则及处理流程，直接看

https://github.com/chika0801/sing-box-examples/blob/main/Tun/config_client_android_remote_dns.json

这里面的dns部分，去测那些dns泄露网站就不会有国内的dns ip

**Comment by onefoxjump** [comment]
谢谢回复，我刚用singbox，官网配置方面的文档看不太懂。请问Android客户端可以直接用在Windows上吗？我看除了"stack": "gvisor"这项配置可能会有影响外，其他的都没影响。[config_client_android_remote_dns.json]的dns规则是：非cn远程DNS，cn本地dns，是这样吗？

**Comment by chika0801** [comment]
> 请问Android客户端可以直接用在Windows上吗

可以样，其实你用对比软件，看下2份的区别，就那点点参数
