### ISSUE TITLE
tun模式下dns配置

### ISSUE THREAD

**Issue by onefoxjump** [chika0801/sing-box-examples#110]
使用[Tun/config_client_android_remote_dns.json]配置，我在服务器上的hosts文件中设置了某些域名的IP地址，但是我设置的这个IP地址好像并没有生效，是不是dns设置的问题？如何在该配置示例的基础上最小化修改能确保服务器上的hosts文件生效呢？

**Comment by chika0801** [comment]
> 如何在该配置示例的基础上最小化修改能确保服务器上的hosts文件生效呢？

这个问题我不知道，没试过你的场景。

**Comment by onefoxjump** [comment]
能否在sing-box客户端的dns设置部分，排除某个域名不进行dns查询而是直接交给服务器，从而实现服务器上的hosts文件中配置的

**Comment by chika0801** [comment]
https://github.com/chika0801/sing-box-examples/blob/main/Tun/self-use/sing-box_client_windows.json#L45-L59

参数这个链接中的配置的这一段，你学习一下fakeip这个关键词的一些知识，就能实现了。

**Comment by onefoxjump** [comment]
谢谢，已解决。
