### ISSUE TITLE
请教大佬dns配置问题

### ISSUE THREAD

**Issue by thincen** [chika0801/sing-box-examples#111]
```
{
"rule_set": "geosite-geolocation-!cn",
"query_type": [
"CNAME"
],
"server": "dns_proxy"
}
```
这一段配置不是`logic`, 是非cn地址或CNAME类型的意思吗?

我现在情况是

在debian12中使用singbox作为透明网关
wifi的dns server是debian的ip
inbound中有
```
{
"type": "direct",
"tag": "dns-in",
"listen": "0.0.0.0",
"listen_port": 53,
"network": "udp"
}
```
rules中有两种模式
```
{inbound: dns-in,outbound: dns-out},
{"protocol": "dns","outbound": "dns-out"}
```
outbound中有
```
{
"type": "dns",
"tag": "dns-out"
}
```

我不清楚bilibili的视频封面图片是否为CNMAE, 用dns_proxy后加载缓慢, 是否因为解析的ip和我本地连接较慢甚至加载不出来。

使用手机5g或更改wifi的dns server为223.5.5.5都可以测试很快加载完成。

谢谢

**Comment by chika0801** [comment]
那段意思是 geosite-geolocation-!cn 类别中的域名查询类型是 cname 的，走 dns_proxy 这个 dns。

**Comment by thincen** [comment]
> 那段意思是 geosite-geolocation-!cn 类别中的域名查询类型是 cname 的，走 dns_proxy 这个 dns。

我之前以为`&&`的操作需要
```
{
  "type": "logical",
  "mode": "and",
  "rules": [],
  "server": ""
}
```
这样的形式表示

**Comment by chika0801** [comment]
这种形式 "rules": [], 中你可以组合各种条件，你不用这种条件，哪些条件是and就看它文档上的说明了，按你自己习惯来写就是了。
