### ISSUE TITLE
Hello. 

### ISSUE THREAD

**Issue by Thaomtam** [chika0801/sing-box-examples#116]
Is there any way when stealing yourself, you can use port 80? I found it by accident "Xboard" Use reverse proxy. Following are the parameters. 
设置反向代理
站点设置 > 反向代理 > 添加反向代理
在 代理名称 填入 Xboard
在 目标URL 填入 http://127.0.0.1:7001 修改反向代理规则为：

location ^~ / {
    proxy_pass http://127.0.0.1:7001;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Real-PORT $remote_port;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header Scheme $scheme;
    proxy_set_header Server-Protocol $server_protocol;
    proxy_set_header Server-Name $server_name;
    proxy_set_header Server-Addr $server_addr;
    proxy_set_header Server-Port $server_port;
    proxy_cache off;
}
Chika, can you guide me? I want to steal myself and use port 80.Thanks sir

**Comment by chika0801** [comment]
I haven't used the program Xboard. I'm guessing you tried filling in http://127.0.0.1:80 at the URL and it worked?

**Comment by Thaomtam** [comment]
> I haven't used the program Xboard. I'm guessing you tried filling in http://127.0.0.1:80 at the URL and it worked?

I was just thinking about it. tks
