### ISSUE TITLE
求助，sing-box 不支持 Proxy Protocol 后如何使用NGINX前置分流

### ISSUE THREAD

**Issue by SuperNG6** [chika0801/sing-box-examples#120]
如题，求助。
因为服务器用途还挺多的（有些网站在上面，443端口只想给NGINX），也不想只运行 sing-box ，现在新版 sing-box 已经不支持 Proxy Protocol ，还有没有其他方法（不想用xray）使用NGINX前置分流？

https://sing-box.sagernet.org/deprecated/

**Comment by chika0801** [comment]
我想了一下，根据这个链接的NGINX配置 

https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-REALITY/nginx_sni_shunting/nginx.conf#L36

proxy_protocol    on; 这参数改下，就不传递 Proxy Protocol 了，至于sing-box你开什么协议组合类型怎么接收，我也没想过了。

**Comment by SuperNG6** [comment]
> 我想了一下，根据这个链接的NGINX配置
> 
> https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-REALITY/nginx_sni_shunting/nginx.conf#L36
> 
> proxy_protocol on; 这参数改下，就不传递 Proxy Protocol 了，至于sing-box你开什么协议组合类型怎么接收，我也没想过了。


/c

> 我想了一下，根据这个链接的NGINX配置
> 
> https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-REALITY/nginx_sni_shunting/nginx.conf#L36
> 
> proxy_protocol on; 这参数改下，就不传递 Proxy Protocol 了，至于sing-box你开什么协议组合类型怎么接收，我也没想过了。

我现在用的 REALITY+H2MUX，NGINX前置SNI分流到sing-box，singbox:v1.5.5版本支持Proxy Protocol ，后续版本不支持。
Nginx proxy_protocol    on 的话 sing-box 会报错
```
    server {
        listen            443;
        listen            [::]:443;
        proxy_pass        $name;
        ssl_preread       on;

        proxy_protocol    on;
    }
```

**Comment by chika0801** [comment]
其实建议你不要难为自己了，sing-box不支持Proxy Protocol你就不要强制自己想办法用嘛，不然事情问题哪里搞得完了。

要么就不用NGINX的SNI分流形式，也是解决问题的思路。参考一下嘛。

**Comment by SuperNG6** [comment]
> 其实建议你不要难为自己了，sing-box不支持Proxy Protocol你就不要强制自己想办法用嘛，不然事情问题哪里搞得完了。
> 
> 要么就不用NGINX的SNI分流形式，也是解决问题的思路。参考一下嘛。

感谢，已解决， sing-box 和nginx 都禁用 Proxy Protocol后成功联通；

**Comment by chika0801** [comment]
sing-box不支持，你在 NGINX配置中不传递，应该就是能通的，你也搞通了就好。
