### ISSUE TITLE
关于安卓配置问题

### ISSUE THREAD

**Issue by onlyzyz** [chika0801/sing-box-examples#15]
大佬您好,我用的是shadow-tls协议,outbounds部分替换了您配置文件中velss部分,结果无法访问,会观察到日志ERROR[0031] dns:exchange failed for gmscompliance-pa.googleapis.com.IN A:context canceled这样的报错,配置文件如下,能否帮忙看看
{
  "log": {
    "level": "info",
    "timestamp": true
  },
    "dns": {
        "servers": [
            {
                "tag": "dns_proxy",
                "address": "tcp://1.1.1.1",
                "address_resolver": "dns_direct",
                "strategy": "ipv4_only", // 若服务端准备好了IPv6，可改为 prefer_ipv6
                "detour": "shadowtls-out"
            },
            {
                "tag": "dns_direct",
                "address": "https://223.5.5.5/dns-query",
                "strategy": "ipv4_only", // 若客户端准备好了IPv6，可改为 prefer_ipv6
                "detour": "direct"
            },
            {
                "tag": "dns_block",
                "address": "rcode://success"
            }
        ],
        "rules": [
            {
                "geosite": [
                    "category-ads-all"
                ],
                "server": "dns_block",
                "disable_cache": true
            },
            {
                "geosite": [
                    "category-games@cn"
                ],
                "server": "dns_direct"
            },
            {
                "geosite": [
                    "geolocation-!cn"
                ],
                "server": "dns_proxy"
            },
            {
                "geosite": [
                    "cn",
                    "private"
                ],
                "server": "dns_direct"
            }
        ]
    },
    "route": {
        "geoip": {
            "download_url": "https://github.com/soffchen/sing-geoip/releases/latest/download/geoip.db"
        },
        "geosite": {
            "download_url": "https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db"
        },
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "geosite": [
                    "category-ads-all"
                ],
                "outbound": "block"
            },
            {
                "type": "logical",
                "mode": "and",
                "rules": [
                    {
                        "geosite": [
                            "category-games@cn"
                        ]
                    },
                    {
                        "geoip": [
                            "cn"
                        ]
                    }
                ],
                "outbound": "direct"
            },
            {
                "geosite": [
                    "geolocation-!cn"
                ],
                "outbound": "shadowtls-out"
            },
            {
                "type": "logical",
                "mode": "and",
                "rules": [
                    {
                        "geosite": [
                            "cn"
                        ]
                    },
                    {
                        "geoip": [
                            "cn"
                        ]
                    }
                ],
                "outbound": "direct"
            },
            {
                "geosite": [
                    "private"
                ],
                "outbound": "direct"
            },
            {
                "geoip": [
                    "cn",
                    "private"
                ],
                "outbound": "direct"
            }
        ],
        "auto_detect_interface": true
    },
    "inbounds": [
        {
            "type": "tun",
            "tag": "tun-in",
            "interface_name": "tun0",
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "fdfe:dcba:9876::1/126",
            "mtu": 9000,
            "auto_route": true,
            "strict_route": true,
            "endpoint_independent_nat": false,
            "stack": "gvisor",
            "sniff": true,
            "sniff_override_destination": false
        }
    ],
    "outbounds": [
        {
            "type": "shadowsocks",
            "method": "chacha20-ietf-poly1305",
            "password": "pawwsd",
            "detour": "shadowtls-out",
            "multiplex": {
              "enabled": true,
              "max_connections": 4,
              "min_streams": 4
          }
        },
        {
            "type": "shadowtls",
            "tag": "shadowtls-out",
            "server": "199.199.199.199",
            "server_port": 443,
            "version": 3,
            "password": "pawwsd",
            "tls": {
              "enabled": true,
              "server_name": "aws.amazon.com",
              "utls": {
                "enabled": false,
                "fingerprint": "chrome"
            }
          }
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ]
}

**Comment by chika0801** [comment]
暂时帮不上你，我没学shadow-tls协议的配置方式。

**Comment by chika0801** [comment]
学了下，帮你看了是这样的
```
    "outbounds": [
        {
            "type": "shadowsocks",
            "tag": "proxy",
            "method": "2022-blake3-aes-128-gcm",
            "password": "8JCsPssfgS8tiRwiMlhARg==",
            "detour": "shadowtls-out",
            "multiplex": {
                "enabled": true,
                "max_connections": 4,
                "min_streams": 4
            }
        },
        {
            "type": "shadowtls",
            "tag": "shadowtls-out",
            "server": "213.232.115.67",
            "server_port": 8443,
            "version": 3,
            "password": "8JCsPssfgS8tiRwiMlhARg==",
            "tls": {
                "enabled": true,
                "server_name": "www.lovelive-anime.jp",
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                }
            }
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ]
```

**Comment by chika0801** [comment]
学了下，帮你看了是这样的
```
    "outbounds": [
        {
            "type": "shadowsocks",
            "tag": "proxy",
            "method": "2022-blake3-aes-128-gcm",
            "password": "8JCsPssfgS8tiRwiMlhARg==",
            "detour": "shadowtls-out",
            "multiplex": {
                "enabled": true,
                "max_connections": 4,
                "min_streams": 4
            }
        },
        {
            "type": "shadowtls",
            "tag": "shadowtls-out",
            "server": "服务端的IP",
            "server_port": 8443,
            "version": 3,
            "password": "8JCsPssfgS8tiRwiMlhARg==",
            "tls": {
                "enabled": true,
                "server_name": "www.lovelive-anime.jp",
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                }
            }
        },
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ]
```

**Comment by onlyzyz** [comment]
> 学了下，帮你看了是这样的
> 
> ```
>         "tag": "proxy",
> ```
> 
> 你加下这个
> 
> ```
>     "outbounds": [
>         {
>             "type": "shadowsocks",
>             "tag": "proxy",
>             "method": "2022-blake3-aes-128-gcm",
>             "password": "8JCsPssfgS8tiRwiMlhARg==",
>             "detour": "shadowtls-out",
>             "multiplex": {
>                 "enabled": true,
>                 "max_connections": 4,
>                 "min_streams": 4
>             }
>         },
>         {
>             "type": "shadowtls",
>             "tag": "shadowtls-out",
>             "server": "服务端的IP",
>             "server_port": 8443,
>             "version": 3,
>             "password": "8JCsPssfgS8tiRwiMlhARg==",
>             "tls": {
>                 "enabled": true,
>                 "server_name": "www.lovelive-anime.jp",
>                 "utls": {
>                     "enabled": true,
>                     "fingerprint": "chrome"
>                 }
>             }
>         },
>         {
>             "type": "direct",
>             "tag": "direct"
>         },
>         {
>             "type": "block",
>             "tag": "block"
>         },
>         {
>             "type": "dns",
>             "tag": "dns-out"
>         }
>     ]
> ```

大佬请接受我的膜拜

**Comment by ErfanCyber10** [comment]
I have a question could u please gime me your telegram id

**Comment by chika0801** [comment]
> I have a question could u please gime me your telegram id

I can't provide you with my telegram id. You can post a question here or go to Xray's telegram group and ask a question.
