### ISSUE TITLE
rules

### ISSUE THREAD

**Issue by yyiwu** [chika0801/sing-box-examples#20]
请问tun模式里面的路由规则为什么要阻断443端口的udp流量

**Comment by chika0801** [comment]
https://github.com/SagerNet/sing-box/issues/587#issuecomment-1534125886

原因见上。意思是你用singbox里的vless协议，flow选了vision，不和xray里flow选vision一个行为（不加-udp）。

udp443能通，至于不推荐代理quic，简单说代理了quic你ytb跑分不好看
