### ISSUE TITLE
Guide to Configuring Server-Side DNS Resolution for Sing-Box (VLESS-XTLS-uTLS-REALITY) to Avoid DNS Pollution Issues

### ISSUE THREAD

**Issue by us254** [chika0801/sing-box-examples#21]
I need help with a DNS resolution problem in sing-box (VLESS-XTLS-uTLS-REALITY). It relies on client-side DNS resolution, causing issues with accessing blocked sites due to DNS pollution. I've been using "Simple DnsCrypt" as a workaround, but I want to configure sing-box for server-side DNS resolution. Can you guide me on this?

**Comment by chika0801** [comment]
You need to provide, your client-side configuration, server-side configuration.

Tell me if your client is for example using windows system? Do you use the TUN mode of sing-box? Tell me how you use it, so I can help you analyze how to modify the configuration file.

**Comment by us254** [comment]
I use "sing-box.exe" in Windows Command Prompt without TUN mode. Only Telegram works, while the Chrome Browser fails to access blocked sites. The sing-box uses client-side DNS to resolve host names of blocked websites. I ran the command "ping youtube.com -4 -S 1.0.0.1" locally on the client side, but it resulted in a failed transmission and a return of a private IP address instead of the actual IP for youtube.com.

server config

```
{
  "log": {
    "level": "info",
    "timestamp": true
  },
  "route": {
    "rules": [
      {
        "network": "udp",
        "port": [
          443
        ],
        "outbound": "block"
      }
    ]
  },
  "inbounds": [
    {
      "type": "vless",
      "tag": "vless-in",
      "listen": "::",
      "listen_port": 443,
      "sniff": false,
      "sniff_override_destination": false,
      "users": [
        {
          "uuid": "chika",
          "flow": "xtls-rprx-vision"
        }
      ],
      "tls": {
        "enabled": true,
        "server_name": "www.lovelive-anime.jp",
        "reality": {
          "enabled": true,
          "handshake": {
            "server": "www.lovelive-anime.jp",
            "server_port": 443
          },
          "private_key": "2KZ4uouMKgI8nR-LDJNP1_MHisCJOmKGj9jUjZLncVU",
          "short_id": [
            "6ba85179e30d4fc2"
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ]
}
```

------
client config

```
{
  "log": {
    "level": "info",
    "timestamp": true
  },
  "route": {
    "rules": [
      {
        "geosite": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      },
      {
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      }
    ]
  },
  "inbounds": [
    {
      "type": "mixed",
      "tag": "mixed-in",
      "listen": "::",
      "listen_port": 10000,
      "domain_strategy": "ipv4_only",
      "set_system_proxy": false
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy",
      "server": "",
      "server_port": 443,
      "uuid": "chika",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "server_name": "www.lovelive-anime.jp",
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "Z84J2IelR9ch3k8VtlVhhs5ycBUlXA7wHBWcBrjqnAw",
          "short_id": "6ba85179e30d4fc2"
        }
      },
      "packet_encoding": "xudp"
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    }
  ]
}
```

**Comment by us254** [comment]
The issue with the client configuration was due to the "domain strategy" parameter being set as "ipv4_only" in the inbound section. However, removing its value completely resolved the problem, allowing successful configuration for browsers and Telegram.

**Comment by chika0801** [comment]
Because the configuration is made to be used in mainland China, you can troubleshoot errors by minimizing the configuration to suit your needs.
