### ISSUE TITLE
小小的请求

### ISSUE THREAD

**Issue by jh0072110** [chika0801/sing-box-examples#22]
老哥
一直在用您的example十分不错感恩！
想请教一下如何实现ipv4/v6的分流呢，您这里没有开讨论只好斗胆发issue了，如果您觉得…不太合适的话我就关了
实在是没查到，sing的example有点少，wiki页面也没扒明白……
不论您是否有空回答都十分感谢！

**Comment by chika0801** [comment]
sing-box作者经常在tg群里表达的，大意是过滤（不喜欢）初级用户，它的风格。

https://github.com/chika0801/sing-box-examples/blob/68a32fee4cea8e67fb781dc974db443d0cd7dbf5/examples/netflix_unlock_select_IPv6.json

你参考这个链接看看，我也不知道你问的是不是这问题（猜差不多）这些内容你如果不是初级用户，看文档也能看懂。

有什么继续回复就是了。

**Comment by jh0072110** [comment]
> sing-box作者经常在tg群里表达的，大意是过滤（不喜欢）初级用户，它的风格。
> 
> https://github.com/chika0801/sing-box-examples/blob/68a32fee4cea8e67fb781dc974db443d0cd7dbf5/examples/netflix_unlock_select_IPv6.json
> 
> 你参考这个链接看看，我也不知道你问的是不是这问题（猜差不多）这些内容你如果不是初级用户，看文档也能看懂。
> 
> 有什么继续回复就是了。

没错就是它！爱你！

**Comment by jh0072110** [comment]
BTW如果想让代理全走v4的话只需要加这一条就可以了是吧
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct_ipv4",
            "domain_strategy": "ipv4_only"
        }

**Comment by chika0801** [comment]
路由部分不写要走V6的分流，出站部分只有这1个且它是在最上面（第1个出站是默认值）

能实现你的目的

或你VPS的网上配置文件你只有V4的内容，不写V6这些，自然只有V4

**Comment by jh0072110** [comment]
> https://github.com/chika0801/sing-box-examples/blob/68a32fee4cea8e67fb781dc974db443d0cd7dbf5/examples/netflix_unlock_select_IPv6.json

哈哈哈哈 这是一个比较极端的情况 就是想用v6中转的情况就要v6入v4出嘛

**Comment by jh0072110** [comment]
> 路由部分不写要走V6的分流，出站部分只有这1个或它是在最上面（第1个出站是默认值）
> 
> 能实现你的目的。
> 
> 你换个思路更直接点，
> 
> 你VPS的网卡配置文件中你只有V4的内容，不写V6，自然只有V4

哈哈哈哈 这是一个比较极端的情况 就是想用v6中转的情况就要v6入v4出嘛
