### ISSUE TITLE
可否增加Linux的Tun示例？

### ISSUE THREAD

**Issue by yjps** [chika0801/sing-box-examples#26]
使用Linux作为旁路由网关，请给个Tun + Fake IP的示例，非常感谢！

**Comment by chika0801** [comment]
我不会这个用法（没用），我也不是什么都会，所以直接告诉你了。

我建议你去 https://sing-box.sagernet.org/ 找那边社区的TG群，去它的群里问。

**Comment by yjps** [comment]
好的，谢谢
