### ISSUE TITLE
[教程]如何在windows下启动即运行，并且最小化

### ISSUE THREAD

**Issue by KoinuDayo** [chika0801/sing-box-examples#27]
将sing-box加入path 或 在脚本内写上sing-box的完整路径

```pwsh
C:\Path\to\sing-box.exe run -c "Z:\path\to\sing-box\config.json" #无需在前面加上start /min
```

打开开始菜单，运行 `Windows工具` 内的 `任务计划程序` 或 使用直接使用搜索功能打开 `任务计划程序` 。  
可选导入，或者自己创建一个基本任务
<details>
<summary>导入</summary>

```xml
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>1970-01-01T00:00:00.0000000</Date>
    <Author>KOINU</Author>
    <URI>\Sing-box Tun</URI>
  </RegistrationInfo>
  <Triggers>
    <BootTrigger>
      <Enabled>true</Enabled>
    </BootTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-987654321-1234567890-987654321-1001</UserId>  <!--换成自己的UserId，或者可以不管，这个是ChatGPT生成的-->
      <LogonType>S4U</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>false</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>Z:\path\to\your\run.bat</Command> <!--换成自己的脚本位置，或者直接把上面的脚本放在这里-->
    </Exec>
  </Actions>
</Task>

```
把这个xml文件保存，在 `任务计划程序` 中导入，导入成功之后会看见多了 `Sing-box Tun`，右键运行

</details>

<details><summary>自己创建</summary>

先随便创建一个基本计划，假设这里你把计划命名为了 `sing-box Tun` ，右键它点击属性      
1. 在安全选项中选择选择 `不管用户是否登入都要运行` ，勾选 `不存储密码。只有访问计算机资源的权限`，勾选 `使用最高权限运行` 。             
2. 创建一个触发器，在 `开始任务` 的下拉栏内选择 `启动时` 。                      
3. 创建一个操作，内容为你脚本的绝对路径，或者把脚本的内容放在这里                        
4. 取消勾选 `设置` 内 `如果任务运行时间超过以下时间，停止任务`          
        
保存，然后运行   
                    
</details>

之后应该就可以让sing-box在后台无窗口运行了

**Comment by KoinuDayo** [comment]
感谢pin

**Comment by chika0801** [comment]
不用客气

**Comment by okaygh** [comment]
> 谢谢pin， 顺便说一句，如果想关闭的话直接右键`Sing-box Tun`点击`结束`，之后进入任务管理器结束`sing-box`进程

请问下为什么按照流程关闭后,下次运行计划任务时,第一次运行后启动不了sing-box(我在任务管理器里看到启动了,但是很快就被关闭了),再运行一次计划任务后台就能正常启动sb不会关闭,这是什么情况

**Comment by KoinuDayo** [comment]
> > 谢谢pin， 顺便说一句，如果想关闭的话直接右键`Sing-box Tun`点击`结束`，之后进入任务管理器结束`sing-box`进程
> 
> 请问下为什么按照流程关闭后,下次运行计划任务时,第一次运行后启动不了sing-box(我在任务管理器里看到启动了,但是很快就被关闭了),再运行一次计划任务后台就能正常启动sb不会关闭,这是什么情况
> 我是直接把内容写在操作里的,试了下用脚本的形式也是需要2次运行才能启动
> ![QQ截图20230807024813](https://github.com/chika0801/sing-box-examples/assets/25192149/51649957-b041-48cc-b09b-89055dbc985d)
> 

可能是sb在退出时还没来得及清理掉虚拟网卡，你可以在脚本内第一行添加 `taskkill` 指令，然后在任务计划程序中设置允许并行运行任务，只需要重新运行任务就会自动杀掉上一个sb，然后打开新的sb。
具体是为什么我也不清楚，因为我没遇到过这种情况。

**Comment by okaygh** [comment]
> > > 谢谢pin， 顺便说一句，如果想关闭的话直接右键`Sing-box Tun`点击`结束`，之后进入任务管理器结束`sing-box`进程
> > 
> > 
> > 请问下为什么按照流程关闭后,下次运行计划任务时,第一次运行后启动不了sing-box(我在任务管理器里看到启动了,但是很快就被关闭了),再运行一次计划任务后台就能正常启动sb不会关闭,这是什么情况
> > 我是直接把内容写在操作里的,试了下用脚本的形式也是需要2次运行才能启动
> > ![QQ截图20230807024813](https://user-images.githubusercontent.com/25192149/258660833-51649957-b041-48cc-b09b-89055dbc985d.png)
> 
> 可能是sb在退出时还没来得及清理掉虚拟网卡，你可以在脚本内第一行添加 `taskkill` 指令杀死sb，然后在任务计划程序中设置允许并行运行任务，只需要重新运行任务就会自动杀掉上一个sb，然后打开新的sb。 具体是为什么我也不清楚，因为我没遇到过这种情况。

大佬说的是对的,我手动终止计划任务后,再次打开,发现计划任务显示是运行了,但是我在网络连接里看并没有创建tun,然后这个计划任务过一会就变成了准备就绪,再次启动计划任务就可以正常创建tun了,用了taskkill指令还是这样,我尝试终止计划任务隔时间长一点再启动也不行,依然需要2次启动才能创建tun...

**Comment by NexusKMT** [comment]
> > > > 谢谢pin， 顺便说一句，如果想关闭的话直接右键`Sing-box Tun`点击`结束`，之后进入任务管理器结束`sing-box`进程
> > > 
> > > 
> > > 请问下为什么按照流程关闭后,下次运行计划任务时,第一次运行后启动不了sing-box(我在任务管理器里看到启动了,但是很快就被关闭了),再运行一次计划任务后台就能正常启动sb不会关闭,这是什么情况
> > > 我是直接把内容写在操作里的,试了下用脚本的形式也是需要2次运行才能启动
> > > ![QQ截图20230807024813](https://user-images.githubusercontent.com/25192149/258660833-51649957-b041-48cc-b09b-89055dbc985d.png)
> > 
> > 
> > 可能是sb在退出时还没来得及清理掉虚拟网卡，你可以在脚本内第一行添加 `taskkill` 指令杀死sb，然后在任务计划程序中设置允许并行运行任务，只需要重新运行任务就会自动杀掉上一个sb，然后打开新的sb。 具体是为什么我也不清楚，因为我没遇到过这种情况。
> 
> 大佬说的是对的,我手动终止计划任务后,再次打开,发现计划任务显示是运行了,但是我在网络连接里看并没有创建tun,然后这个计划任务过一会就变成了准备就绪,再次启动计划任务就可以正常创建tun了,用了taskkill指令还是这样,我尝试终止计划任务隔时间长一点再启动也不行,依然需要2次启动才能创建tun...

复现了你的问题，解决方法：“计划任务直接运行带有singbox指令的批处理文件”

**Comment by chise0713** [comment]
如果这是bash的话我可以在脚本里加个trap，如果收到终止信号就kill掉$！，但是这是bat（

**Comment by lateautumn2** [comment]
你好，请问下，我windows用singbox cli  sing-box run / start \min sing-box run 之后会有个sing-box控制台日志窗口，请问这个窗口可以隐藏掉吗

**Comment by lateautumn2** [comment]
> 你好，请问下，我windows用singbox cli sing-box run / start \min sing-box run 之后会有个sing-box控制台日志窗口，请问这个窗口可以隐藏掉吗

已使用nssm解决
