### ISSUE TITLE
大佬，请指导怎样把若干代理协议同时集中在一个服务端的config.json里。

### ISSUE THREAD

**Issue by needhumanity** [chika0801/sing-box-examples#32]
sing-box给人以搭积木的感觉,但是怎样将不同代理协议,以不同端口的方式并存,对我来说有难度.
特别恳请大佬设计一下多代理同时共存的示例.
谢谢.

**Comment by chika0801** [comment]
这要我怎么说了，就从模板复制粘贴到一起，注意下各协议监听的端口不一样，你要问，你自己先试试，把你的配置粘上来帮你看看。一来就伸手我想帮也没法。这样的。
