### ISSUE TITLE
关于tun配置文件客户端dns部分

### ISSUE THREAD

**Issue by TingTing1990** [chika0801/sing-box-examples#34]
用大佬的tun客户端配置，有些域名dns解析有问题导致无法连接上，我想这个域名走系统dns解析，所以我在dns服务器部分新增一个系统解析的服务器，然后规则加上这个域名，大佬帮忙看下对不对，谢谢！

{
  "dns": {
      "server": [
            {
                "tag": "dns_local",
                "address": "local",
                "strategy": "ipv4_only",
                "detour": "direct"
            }
],
   "rules": [
        {
        "domain_suffix": [
          "域名.com"
        ]
     }
   "server": "dns_local"
     ]
   }
  }

**Comment by chika0801** [comment]
"address": "dhcp://auto",

win系统上用默认系统的dns要用上面的，不是用local

**Comment by TingTing1990** [comment]
多谢，其他的写法没问题吧？

**Comment by chika0801** [comment]
> 多谢，其他的写法没问题吧？
> 
> 那么Mac上也要这样吗？ "address": "dhcp://auto",

其它没看出问题。

mac我不清楚能不能写 dhcp://auto ，建议你去sing-box的tg群问那边。

**Comment by TingTing1990** [comment]
> > 多谢，其他的写法没问题吧？
> > 那么Mac上也要这样吗？ "address": "dhcp://auto",
> 
> 其它没看出问题。
> 
> mac我不清楚能不能写 dhcp://auto ，建议你去sing-box的tg群问那边。

多谢，在Mac上用的配置文件就是 dhcp://auto ，没问题
