### ISSUE TITLE
Converting xray DNS to sing-box DNS

### ISSUE THREAD

**Issue by alidxdydz** [chika0801/sing-box-examples#35]
Hello,

I use this config in xray to manage DNS.

```
{
  "dns": {
    "tag": "dns",
    "hosts": {
      "dns.cloudflare.com": [
        "104.16.132.229",
        "104.16.133.229",
        "1.1.1.1",
        "1.0.0.1"
      ],
      "domain:youtube.com": [
        "google.com"
      ]
    },
    "servers": [
      "https://dns.cloudflare.com/dns-query",
      "https://cloudflare-dns.com/dns-query"
    ]
  }
}
```

The important part is I resolve some of domains myself by providing IPs or mapping 2 domains to each other which have same IPs.

I wonder how can I achieve this in sing-box?

**Comment by chika0801** [comment]
http://sing-box.sagernet.org/zh/configuration/dns/rule/

I read the link and I don't think the features you want are provided in the sing-box. I suggest you go to sing-box's gitbub and post an iss for help.

**Comment by chika0801** [comment]
"hosts": {
      "dns.cloudflare.com": [
        "104.16.132.229",
        "104.16.133.229",
        "1.1.1.1",
        "1.0.0.1"
      ],


You're asking about this part of the xray configuration and how it's implemented in sing-box, right?

**Comment by alidxdydz** [comment]
In this example, dns.cloudflare.com resolves to 104.16.132.229, 104.16.133.229, 1.1.1.1 and 1.0.0.1 only.
Or youtube.com is resolved with google.com IPs.

How is this possible in sing-box?

**Comment by chika0801** [comment]
> In this example, dns.cloudflare.com resolves to 104.16.132.229, 104.16.133.229, 1.1.1.1 and 1.0.0.1 only. Or youtube.com is resolved with google.com IPs.
> 
> How is this possible in sing-box?

From what I know, this cannot be accomplished in sing-box.

**Comment by alidxdydz** [comment]
Thank you for your response

**Comment by chika0801** [comment]
https://sing-box.sagernet.org/zh/support/

If you need to go to Sing-box's community for help, you can contact them here.

**Comment by alidxdydz** [comment]
I will contact them for sure.
Thank you
