### ISSUE TITLE
wifi hotspot

### ISSUE THREAD

**Issue by Ley-VN** [chika0801/sing-box-examples#39]
i'm using tun mode
Can you give me an example configuration?
I want to configure LAN.

**Comment by chika0801** [comment]
https://github.com/chika0801/sing-box-examples/blob/main/Tun/config_client_windows.json

This is the configuration I use for myself.

**Comment by Ley-VN** [comment]
I use my android phone to share the network

**Comment by chika0801** [comment]
> I use my android phone to share the network

I don't use an android phone and run Sing-box on my phone. other devices, such as a computer connect in through the android phone's WIFI hotspot and then share the network. I haven't done this, I don't have the experience to help you.

**Comment by Ley-VN** [comment]
Thank you friend
I use 172.19.0.1/30 successful connection.
The wifi receiver must have sing-box installed
Same configuration as above. when using ios. Failed to download geosite. Report error eof. How to solve this problem?

**Comment by chika0801** [comment]
Post your sing-box configuration here and pay attention to the typographical formatting so I can analyze the logic when I see it.
