### ISSUE TITLE
关于sing-box官方文档的已知问题

### ISSUE THREAD

**Issue by TingTing1990** [chika0801/sing-box-examples#41]
![CleanShot 2023-09-03 at 12 54 12@2x](https://github.com/chika0801/sing-box-examples/assets/51083586/457e0e86-8109-4b1b-9505-f99c7b1df375)

看tun的示例文件是否有这个问题，看到开启了自动路由没有开启严格路由

**Comment by chika0801** [comment]
画框中的问题：我不用安卓中的私人DNS，我没测试过当用了时， `"strict_route": false,` 有什么效果，不能回答你。

为什么我是默认给关的：当早也是开，后来看了它文档这段话，试了下关和开，以测试DNS泄露网站结果来看没发现区别，就给的关了。

```
strict_route
启用 auto_route 时执行严格的路由规则。

在 Linux 中:

让不支持的网络无法到达
将所有连接路由到 tun
它可以防止地址泄漏，并使 DNS 劫持在 Android 上工作，但你的设备将无法其他设备被访问。
```

**Comment by chika0801** [comment]
你要用开和关，自己看下吧了。

**Comment by TingTing1990** [comment]
> 画框中的问题：我不用安卓中的私人DNS，我没测试过当用了时， `"strict_route": false,` 有什么效果，不能回答你。
> 
> 为什么我是默认给关的：当早也是开，后来看了它文档这段话，试了下关和开，以测试DNS泄露网站结果来看没发现区别，就给的关了。
> 
> ```
> strict_route
> 启用 auto_route 时执行严格的路由规则。
> 
> 在 Linux 中:
> 
> 让不支持的网络无法到达
> 将所有连接路由到 tun
> 它可以防止地址泄漏，并使 DNS 劫持在 Android 上工作，但你的设备将无法其他设备被访问。
> ```

我开关试了下，开了严格路由在ipcheck网站看不到cn的，开了就只有vps所在地的

**Comment by chika0801** [comment]
我很久前试的，平时也没用SFA客户端。用的配置就是我放上来这套。我现在不再试了，我去把这参数改成开得了。
