### ISSUE TITLE
singbox 反馈

### ISSUE THREAD

**Issue by univerioiln233** [chika0801/sing-box-examples#42]
.\sing run -c 
INFO[0000] router: updated default interface 以太网  5, index 38
INFO[0000] inbound/socks[socks-in]: tcp server started at [::1]:

有多个以太网
已经调高以太网 5的跃迁点
但仍自动试别5

**Comment by chika0801** [comment]
I can't help you with that one. I suggest you to go to sing-box's homepage, it has official support contact information.
