### ISSUE TITLE
dns_proxy问题求教

### ISSUE THREAD

**Issue by jaesony** [chika0801/sing-box-examples#44]
"tag": "dns_proxy",
                "address": "https://1.1.1.1/dns-query",
                "address_resolver": "dns_direct",
                "strategy": "ipv4_only", // 若服务端准备好了IPv6，可改为 prefer_ipv6
                "detour": "proxy"
安卓客户端reality、vision连接没问题。tuic和hysteria连不上，显示dns_proxy loopback，将1.1.1.1改为自建dns服务器才连的上。
感觉dns_proxy没走代理，请问什么问题。

**Comment by chika0801** [comment]
你安卓用的SFA吗？如果是，你发下你的配置，我看到配置才能分析下。

**Comment by jaesony** [comment]
用的是sing-box原版的安卓软件，配置参考的您这个，服务器没用sing-box，不知道是哪方面原因

**Comment by chika0801** [comment]
你不愿意发你的配置，我也不能帮到你。请参考

> 建议你去sing-box那边发帖子问下
