### ISSUE TITLE
[QUESTION] Only listen on ipv6

### ISSUE THREAD

**Issue by bart3nder** [chika0801/sing-box-examples#45]
Hi! Thanks for the examples.
As the title says, In TUIC server config, how can I only listen on ipv6? with ` "listen": "::",`, I can still connect to server with my ipv4 too and I want the server only be accessible via ipv6.

**Comment by chika0801** [comment]
`"listen": "[::]",`

`"listen": "::1",`

This is the answer given by the asking AI, you tested it.

**Comment by chika0801** [comment]
I suggest you go to sing-box's github and ask a question. I can't help you any further.
