### ISSUE TITLE
The newly updated tun configuration failed

### ISSUE THREAD

**Issue by Ley-VN** [chika0801/sing-box-examples#49]
![Screenshot_2023-09-21-21-11-45-168_io nekohasekai sfa](https://github.com/chika0801/sing-box-examples/assets/129369227/d9187a1f-9ca1-4faf-ae93-9e16cdb5d961)
Here is my configuration, help me
{
  "log": {
    "level": "trace",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "dns_Ley",
        "address": "https://1.1.1.1/dns-query",
        "address_resolver": "dns_resolver",
        "strategy": "ipv4_only",
        "detour": "Ley"
      },
      {
        "tag": "dns_direct",
        "address": "https://dns.alidns.com/dns-query",
        "address_resolver": "dns_resolver",
        "strategy": "ipv4_only",
        "detour": "direct"
      },
      {
        "tag": "dns_block",
        "address": "rcode://success"
      },
      {
        "tag": "dns_resolver",
        "address": "223.5.5.5",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "domain": "time.apple.com",
        "server": "dns_resolver"
      },
      {
        "geosite": "category-ads-all",
        "server": "dns_block",
        "disable_cache": true
      },
      {
        "geosite": "geolocation-!cn",
        "server": "dns_Ley"
      },
      {
        "geosite": [
          "cn",
          "private"
        ],
        "server": "dns_direct"
      },
      {
        "outbound": "any",
        "server": "dns_resolver"
      }
    ]
  },
  "ntp": {
    "enabled": true,
    "interval": "30m0s",
    "server": "time.apple.com",
    "server_port": 123,
    "detour": "direct"
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "mtu": 1400,
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": true,
      "include_package": [
        "com.google.android.gms",
        "com.google.android.gsf",
        "com.android.vending",
        "com.android.chrome",
        "org.telegram.messenger"
      ],
      "stack": "gvisor",
      "sniff": true,
      "sniff_override_destination": true
    }
  ],
  "outbounds": [
    {
      "type": "selector",
      "tag": "Ley",
      "outbounds": [
        "LeyVN:80",
        "LeySG:80",
        "LeyVN:443",
        "LeySG:443"
      ],
      "default": "LeySG:443"
    },
    {
      "type": "vless",
      "tag": "LeyVN:80",
      "server": "cloud.ley.vn",
      "server_port": 80,
      "uuid": "....",
      "transport": {
        "type": "http",
        "path": "/Ley.VN",
        "method": "GET",
        "headers": {
          "Host": "dl.kgvn.garenanow.com"
        }
      }
    },
    {
      "type": "vless",
      "tag": "LeySG:80",
      "server": "cloud1.ley.vn",
      "server_port": 80,
      "uuid": "....",
      "transport": {
        "type": "http",
        "path": "/Ley.VN",
        "method": "GET",
        "headers": {
          "Host": "dl.kgvn.garenanow.com"
        }
      }
    },
    {
      "type": "trojan",
      "tag": "LeyVN:443",
      "server": "cloud.ley.vn",
      "server_port": 443,
      "password": "....4",
      "tls": {
        "enabled": true,
        "server_name": "dl.kgvn.garenanow.com",
        "insecure": true
      }
    },
    {
      "type": "trojan",
      "tag": "LeySG:443",
      "server": "cloud1.ley.vn",
      "server_port": 443,
      "password": "....."
      "tls": {
        "enabled": true,
        "server_name": "dl.kgvn.garenanow.com",
        "insecure": true
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "geoip": {
      "download_url": "https://github.com/soffchen/sing-geoip/releases/latest/download/geoip.db"
    },
    "geosite": {
      "download_url": "https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db"
    },
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "protocol": "quic",
        "outbound": "block"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      },
      {
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "geosite": "geolocation-!cn"
          },
          {
            "geoip": "cn",
            "invert": true
          }
        ],
        "outbound": "Ley"
      },
      {
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "geosite": "cn"
          },
          {
            "geoip": "cn"
          }
        ],
        "outbound": "direct"
      },
      {
        "geosite": "private",
        "outbound": "direct"
      },
      {
        "geoip": [
          "cn",
          "private"
        ],
        "outbound": "direct"
      }
    ],
    "auto_detect_interface": true
  }
}

**Comment by chika0801** [comment]
```
{
"tag": "dns_direct",
"address": "https://dns.alidns.com/dns-query",
"address_resolver": "dns_resolver",
"strategy": "ipv4_only",
"detour": "direct"
},
```

```
{
"tag": "dns_resolver",
"address": "223.5.5.5",
"detour": "direct"
}
```

"address": "https://dns.alidns.com/dns-query",

This DNS resolves the domain name of your cloud.ley.vn server.

This DNS's own domain, dns.alidns.com, will resolve using 223.5.5.5.

If you are not in mainland China, please change it to 1.1.1.1.

**Comment by chika0801** [comment]
```
{
"tag": "dns_direct",
"address": "https://1.1.1.1/dns-query",
"address_resolver": "dns_resolver",
"strategy": "ipv4_only",
"detour": "direct"
},
{
"tag": "dns_resolver",
"address": "1.1.1.1",
"detour": "direct"
}

You can try it.
```

**Comment by Ley-VN** [comment]
No fix.I send vps information. Can you help me arrange time?

**Comment by chika0801** [comment]
Try the config file that worked before you modified it, does that config work now?

**Comment by chika0801** [comment]
There are 2 methods of debugging

1 You're still in SFA, post the logs (should be easier to take a screenshot)

2 You test it on your computer, change some parts of the configuration that are different from the Android side. the TUN inbound and outbound DNS routing parts are basically the same, then see if you can't connect to the server, and if you can't, post the log. If you will analyse the log, you can also try to look at the log to find the reason.

**Comment by Ley-VN** [comment]
The old configuration still works normally. I will find a solution. Thank you

**Comment by Ley-VN** [comment]
{
      "type": "trojan",
      "tag": "LeyVN:443",
      "server": "domain.com",
      "server_port": 443,
      "password": "Ley",
      "tls": {
        "enabled": true,
        "server_name": "dl.kgvn.garenanow.com",
        "insecure": true
      }
    }
This configuration works
{
      "type": "tuic",
      "tag": "LeySG:Speed",
      "server": "domain.com",
      "server_port": 8443,
      "uuid": "....",
      "password": "Ley",
      "congestion_control": "bbr",
      "tls": {
        "enabled": true,
        "server_name": "dl.kgvn.garenanow.com",
        "alpn": "h3"
      }
    }
Tuic configuration is not working
=>> I use sni "dl.kgvn.garenanow.com" using 4g. Trojan works, tuic doesn't

**Comment by chika0801** [comment]
The domain name in your TUIC configuration dl.kgvn.garenanow.com 

Do you really have this domain name and have configured the path to the SSL certificate in your server-side configuration in order to apply for it and upload it to your VPS?

**Comment by Ley-VN** [comment]
This domain name is a way for me to use unlimited 4g network traffic. This domain name is an intermediary of the network operator. I used vless configuration and trojan both were successful

**Comment by chika0801** [comment]
The form you're talking about is what we call free traffic with your carrier.

But the protocol TUIC doesn't support this method, it wants you to have your own SSL certificate, which is why you keep failing. You need to figure out the fundamental difference.

**Comment by Ley-VN** [comment]
> Hình thức bạn đang nói đến là cái mà chúng tôi gọi là lưu lượng truy cập miễn phí với nhà cung cấp dịch vụ của bạn.
> 
> Nhưng giao thức TUIC không hỗ trợ phương pháp này, nó muốn bạn có chứng chỉ SSL của riêng mình, đó là lý do tại sao bạn liên tục thất bại. Bạn cần phải tìm ra sự khác biệt cơ bản.

Thank you. It's sad that this new protocol doesn't support that

**Comment by Ley-VN** [comment]
After a few exchanges, you clearly understood my needs and configuration.
Another thing that I haven't been able to do yet is to share wifi with other devices via hotpot.
For example, with v2ray I enable network sharing. The http proxy will be 26.26.26.1/10809
With the sing-box I have configured the inbound part as mixed-in. Listen is 0.0.0.0 or 127.0.0.1. any port. The network receiver cannot connect

**Comment by chika0801** [comment]
For example, you are using SFA on your mobile phone, and you have turned on the WIFI hotspot function on your mobile phone. Other mobile phones connect to this hotspot WIFI, and they are in the WIFI setup page on the options, I remember there is the option, means to choose to use the proxy, the address should be the IP on your mobile phone (mobile phone at this time is the gateway, for example, the guest end to get the IP is 192.168.10.99, the gateway is 192.168.10.1, fill in the 10.1 one), the port is for example 20000, this port number is set in the SFA configuration. You then go into the SFA software in your mobile phone and modify the sing-box configuration to add mixed-in inbound. I remember the parameter: "listen": "::", here you can only write :::, so that other mobile phones can connect to the proxy site. I've tried 127.0.0.1, and other mobile phones don't work.)
  "listen_port": 20000, this 20000 port corresponds to the one mentioned earlier.

**Comment by Ley-VN** [comment]
{
  "log": {
    "level": "info",
    "timestamp": true
  },
  "dns": {
    "servers": [
      {
        "tag": "dns_Ley",
        "address": "https://dns.nextdns.io/b2c627",
        "address_resolver": "dns_local",
        "strategy": "ipv4_only",
        "detour": "Ley"
      },
      {
        "tag": "dns_direct",
        "address": "1.1.1.1",
        "address_resolver": "dns_local",
        "strategy": "ipv4_only",
        "detour": "direct"
      },
      {
        "tag": "dns_block",
        "address": "rcode://success"
      },
      {
        "tag": "dns_local",
        "address": "local",
        "detour": "direct"
      }
    ],
    "rules": [
      {
        "geosite": "category-ads-all",
        "server": "dns_block",
        "disable_cache": true
      },
      {
        "outbound": "any",
        "server": "dns_local"
      }
    ]
  },
  "inbounds": [
    {
      "type": "tun",
      "mtu": 1400,
      "inet4_address": "172.19.0.1/30",
      "auto_route": true,
      "strict_route": true,
      "stack": "gvisor",
      "sniff": true
    },
    {
      "type": "mixed",
      "tag": "mixed-in",
      "listen": "::",
      "listen_port": 10809
    }
  ],
  "outbounds": [
    {
      "type": "selector",
      "tag": "Ley",
      "outbounds": [
        "LeyVN:80",
        "LeySG:80",
        "LeyVN:443",
        "LeySG:443"
      ],
      "default": "LeyVN:443"
    },
    {
      "type": "vless",
      "tag": "LeyVN:80",
     
      "server": "cloud.ley.vn",
      "server_port": 80,
      "uuid": "....",
      "transport": {
        "type": "http",
        "path": "/Ley",
        "method": "GET",
        "headers": {
          "Host": "dl.kgvn.garenanow.com"
        }
      }
    },
    {
      "type": "vless",
      "tag": "LeySG:80",
     
      "server": "cloud.1ley.vn",
      "server_port": 80,
      "uuid": "...",
      "transport": {
        "type": "http",
        "path": "/Ley",
        "method": "GET",
        "headers": {
          "Host": "dl.kgvn.garenanow.com"
        }
      }
    },
    {
      "type": "trojan",
      "tag": "LeyVN:443",
     
      "server": "103.166.183.116",
      "server_port": 443,
      "password": "....",
      "tls": {
        "enabled": true,
        "server_name": "dl.kgvn.garenanow.com",
        "insecure": true
      }
    },
    {
      "type": "trojan",
      "tag": "LeySG:443",
      
      "server": "cloud1.ley.vn",
      "server_port": 443,
      "password": "...",
      "tls": {
        "enabled": true,
        "server_name": "dl.kgvn.garenanow.com",
        "insecure": true
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "protocol": "quic",
        "outbound": "block"
      },
      {
        "geosite": "category-ads-all",
        "outbound": "block"
      }
    ],
    "auto_detect_interface": true
  }
}
The traffic comes directly from the user package, not through the network carrier's network (it runs out of space and cannot be accessed). But v2ray is not needed .

**Comment by Ley-VN** [comment]
Inflexible. 4g IP is dynamic IP. Not a static ip.
V2ray is static ip 26.26.26.1
Shadowrocket static ip is 198.18.0.3 tun server or loopack 127.0.0.1
According to your method, each time you have to change your network's IP automatically

**Comment by chika0801** [comment]
The process I tried was. pc computer (WIN11) with sing-box.exe in TUN mode, and then listen to an additional socks port like 9090. the listen parameter in the configuration is filled in "::". Assuming PC's LAN IP is 192.168.10.12.

The mobile phone and computer are connected to the same LAN. Enter the WIFI settings interface in the mobile phone settings, there is a proxy option, select the option, fill in 192.168.10.12 for the host name and 9090 for the port, and it is normal to access the proxy website on the mobile phone at this time. You can see the log in the sing-box.exe window of your computer.

As for you take the computer I mentioned, and replace it with a mobile phone, which uses the SFA programme, how the configuration file for the SFA programme is going to be written I'm not sure what you're doing. Then after you enable the hotspot on this phone. The other mobile phone connects to this hotspot, and you have to try it yourself how to fill in the proxy option in the WIFI settings of the other mobile phone. I haven't tried it myself.

**Comment by Ley-VN** [comment]
No need for LAN IP
I use ip tun 172.19.0.1 combined with port 20000 mixed-in. Connection successful. On any device, both computer and phone

**Comment by Ley-VN** [comment]
Friend
{
"tag": "dns_direct",
"address": "https://1.1.1.1/dns-query",
"address_resolver": "dns_resolver",
"strategy": "ipv4_only",
"detour": "direct"
},
{
"tag": "dns_resolver",
"address": "1.1.1.1", Change to "local"
"detour": "direct"
}
Because if your home network is offline, you can still launch the configuration normally. If you enter 1.1.1.1 without an internet connection you cannot boot
