### ISSUE TITLE
wireguard.md获取warp账号

### ISSUE THREAD

**Issue by Pacio** [chika0801/sing-box-examples#51]
获取的应该是免费账号吧？好像是有限速~
我想替换成电报群找到的收费key怎么操作

**Comment by chika0801** [comment]
> 获取的应该是免费账号吧？好像是有限速~

没有，速度多快和你VPS的CPU性能有关（跑speedtest时），最快是用内核wireguard，在600-700Mbps

> 我想替换成电报群找到的收费key怎么操作

我没用过不清楚，另外用了warp+的KEY并不会让你觉得日常变快。

建议你去 https://gitlab.com/fscarmen/warp 这儿看看
