### ISSUE TITLE
这个可以远程DNS吗？不让他使用客户端的dns

### ISSUE THREAD

**Issue by do02fw** [chika0801/sing-box-examples#52]
https://github.com/chika0801/sing-box-examples/blob/main/Shadowsocks/config_server.json

**Comment by chika0801** [comment]
远程DNS？你指什么

你要说你客户端是什么环境，或发配置，你的目的之类 。这样的提问不能帮你。

**Comment by chika0801** [comment]
你客户端配置中不全路由规则，这样请求就全发到服务端，自然使用服务端的DNS和路由规则。前提是客户端是http/socks代理环境
如果客户端是tun（透明代理）不可能不在客户端作DNS请求，除非你用用Fakeip。
