### ISSUE TITLE
这个配置有DNS泄露，和HY2的一样

### ISSUE THREAD

**Issue by do02fw** [chika0801/sing-box-examples#53]
https://github.com/chika0801/sing-box-examples/tree/main/Shadowsocks

**Comment by do02fw** [comment]
![image](https://github.com/chika0801/sing-box-examples/assets/138294823/5074eaf8-807c-4455-baac-cb77277ffd2c)

**Comment by do02fw** [comment]
不如萝莉好看

**Comment by chika0801** [comment]
是的，示例故意是最小化原则。

**Comment by do02fw** [comment]
有没有办法解决dns泄露

**Comment by chika0801** [comment]
https://github.com/chika0801/sing-box-examples/tree/main/Tun

用这里的配置，去那些检测网站测不出来泄露

**Comment by chika0801** [comment]
你发的是一个服务端配置，服务端在VPS上通常不开TUN模式。

**Comment by do02fw** [comment]
BUG太多了，看这里，我已经气的不用了，https://github.com/MatsuriDayo/nekoray/issues/900

**Comment by do02fw** [comment]
tun模式不如openvpn和wireguard，这两个tun是最好的，没有任何bug
