### ISSUE TITLE
Why can it only be started once...and then it cannot be started again?

### ISSUE THREAD

**Issue by zhouxinghong** [chika0801/sing-box-examples#54]
Why can it only be started once...and then it cannot be started again?
Windows 10
sing-box 1.4.6

**Comment by chika0801** [comment]
You didn't provide logs, and your config file, I can't help you.

I suggest you go to the official sing-box github page and post for help.

**Comment by zhouxinghong** [comment]
```
    "outbounds": [
   {
      "type": "vmess",
      "tag": "proxy",
      "server": "udpn.poiyo-idc.top",
      "server_port": 80536,
      "uuid": "91054ec1-8645-4613-8169-fda5827c23fb",
      "security": "auto",
      "alter_id": 0,
      "transport": {
        "type": "ws",
        "path": "/gitee",
        "headers": {
          "Host": "udpn.poiyo-idc.top"
        }
      }
    },
```
Other configurations have not been modified and are completely in accordance with the default example.

**Comment by zhouxinghong** [comment]
After the first startup, after I exited by ending the process through the task manager, it could no longer be started.

**Comment by zhouxinghong** [comment]
Launched via the following batch process
start /min sing-box.exe run

**Comment by chika0801** [comment]
From the analysis of the phenomenon you said, I think there is a problem with your configuration, or less and administrator rights to start the program, so sing-box program error.

My test method is, in the windows system, set to enter the terminal programme, there is an option to always start with administrator in the setup options.

Then I start a terminal programme (with administrator privileges) and enter the command sing-box.exe run (you have to enter the path to the sing-box folder beforehand). At this point, if there are any errors reported, the terminal programme window does not message and you can see what the log shows. In order to do the next step in the analysis to find the cause.

**Comment by zhouxinghong** [comment]
Thank you for your help! I will try your method again. 👍👏😜

**Comment by chika0801** [comment]
There is another way. In the CMD window, you type sing-box -h. I remember that there is a command check. you add the name of your configuration file with this command, and it will check if there are any errors in your configuration. If you check this way there are no errors. If you run the batch file with administrator privileges, and the command window still flashes back, you have to start the CMD window with administrator privileges as I replied to you earlier, and run the command sing-box.exe run, and then analyse the reason through the error message.

**Comment by zhouxinghong** [comment]
Thank you very much for your attentive help! 👍👏😜
I have a few questions that I would like to ask you:
1. Is there any command in the terminal that can stop and exit the program?
2. How to switch service nodes?
3. How to update the service node?

**Comment by chika0801** [comment]
> Is there any command in the terminal that can stop and exit the program?

ctrl+c

> How to switch service nodes?

I have only 1 outbound (proxy) in my configuration. I'm not a CLASH user, I'm not a purchaser of the service provided by the merchant, so for me I don't have the need to switch nodes from that panel of the CLASH client. If you look at the sing-box website, there is support for the CLASH panel and the Selector parameter of the configuration file.

> How to test the delay time and speed of the service node?

How to test that you can ping your VPS's IP locally, and that you can use route tracing on the VPS to measure the backhaul route to your local IP. These should not be questions for sing-box configuration issues. The only relevant one is the parameter https://sing-box.sagernet.org/zh/configuration/outbound/urltest/

**Comment by zhouxinghong** [comment]
Thank you very much! I need to study more uses of it😜👍
