### ISSUE TITLE
wireguard.md里面套warp的方法在更新sing-box正式版1.5.0之后失效~

### ISSUE THREAD

**Issue by Pacio** [chika0801/sing-box-examples#55]
之前用的pre分支内核都可以正常套，不知道为什么更新了正式版内核后warp就失效了

**Comment by chise0713** [comment]
看看log和配置文件

**Comment by Pacio** [comment]
> 看看log和配置文件

{
  "log": {
    "disabled": false,
    "level": "info",
    "timestamp": true
  },
  "route": {
  
        "geosite":{
            "download_url":"https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db",
            "download_detour":"INTERNET_OUT"
        },
        "geoip":{
            "download_url":"https://github.com/soffchen/sing-geoip/releases/latest/download/geoip.db",
            "download_detour":"INTERNET_OUT"
        },
  
        "rules": [
            {
                "domain": [
                
                    "ai.com"                    
                ],
                
                "geosite": [
                
                    "openai"
                ],
                
                "outbound": "warp-IPv4-out"
            }
        ]
    },
  
  "inbounds": [
    {
      "sniff": true,
      "sniff_override_destination": true,
     
    }
  ],
  "outbounds": [
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    
    {
            "type": "direct",
            "tag": "warp-IPv4-out",
            "detour": "wireguard-out",
            "domain_strategy": "ipv4_only"
    },
    {
            "type": "direct",
            "tag": "warp-IPv6-out",
            "detour": "wireguard-out",
            "domain_strategy": "ipv6_only"
    },
    {
            "type": "wireguard",
            "tag": "wireguard-out",
            "server": "engage.cloudflareclient.com",  
            "server_port": 2408,
            "local_address": [
                "172.16.0.2/32",
                "2606:4700:110:8fcb:f1:2074:8c2e:f451/128" 
            ],
            "private_key": "WAEFyoKK6QrAuWmIX04mZlgs1eEmz+MM5Dlx8PDC8UY=", 
            "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "reserved":[97,58,253], 
            "mtu": 1280
    }
  ]
}

**Comment by chika0801** [comment]
我这不做这个售后，建议去sb的TG群问，或去它的iss区发帖子问。

**Comment by chika0801** [comment]
这个不会是你发的吧？

https://t.me/yapug/31932

**Comment by Pacio** [comment]
> 这个不会是你发的吧？
> 
> https://t.me/yapug/31932

不是我发的，目前差不多搞清了，1.5.0套hysteria2协议才会出现失效情况,其他协议正常
