### ISSUE TITLE
Admin please guide me to sing-box reality to steal myself

### ISSUE THREAD

**Issue by Thaomtam** [chika0801/sing-box-examples#57]
I have been an ad follower for a long time. Thank you all for your dedication. Thank you

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/steal_oneself/nginx.conf

Use this nginx configuration file

https://github.com/chika0801/Xray-examples/blob/66d6638892b890cae868ef37bf38c2bba3e10da9/VLESS-XTLS-uTLS-REALITY/steal_oneself/nginx.conf#L49

proxy_protocol `Delete this parameter`

**Comment by chika0801** [comment]
Your nginx logs for visitors (not your own IP, your own IP is shown in the xray logs. The IP of the person visiting your VPS only shows 127.0.0.1. this is not a big deal, and is usually not noticed in the nginx logs.

**Comment by Thaomtam** [comment]
> https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/steal_oneself/nginx.conf
> 
> Use this nginx configuration file
> 
> https://github.com/chika0801/Xray-examples/blob/66d6638892b890cae868ef37bf38c2bba3e10da9/VLESS-XTLS-uTLS-REALITY/steal_oneself/nginx.conf#L49
> 
> proxy_protocol `Delete this parameter`

![Screenshot_2023-10-03-23-31-39-065_com.rhmsoft.edit.pro.jpg](https://github.com/chika0801/sing-box-examples/assets/109426941/f6b6fdf6-bb8c-4972-b426-92a19afe15dc)

like this, isn't it, admin?

**Comment by chika0801** [comment]
yes

**Comment by Thaomtam** [comment]
> yes

One more problem sir.If I use shadowtls and vless reality singbox. Is it possible to handshake reality to the server port of shadowtls? For example, I want reality to connect through shadowtls, shadowtls communicates outside. and vless reality connects to shadowtls Like connecting to steal yourself via 127.0.0.1 port 8001. Tks ad

**Comment by Thaomtam** [comment]
> yes

One more problem sir.If I use shadowtls and vless reality singbox. Is it possible to handshake reality to the server port of shadowtls? For example, I want reality to connect through shadowtls, shadowtls communicates outside. and vless reality connects to shadowtls Like connecting to steal yourself via 127.0.0.1 port 8001. Tks ad

**Comment by chika0801** [comment]
no

**Comment by Thaomtam** [comment]
tks sir

**Comment by Thaomtam** [comment]
> no

I have 1 question. Is there any way for singbox to use the same port as xray? I follow admin's xray as fallback so it can be used together.How to do singbox?

**Comment by Thaomtam** [comment]
> no

I have 1 question. Is there any way for singbox to use the same port as xray? I follow admin's xray as fallback so it can be used together.How to do singbox?

**Comment by chika0801** [comment]
TCP port, 2 programmes cannot listen to the same port at the same time.

If one application listens on UDP443, another application can listen on TCP443.

**Comment by Thaomtam** [comment]
> TCP port, 2 programmes cannot listen to the same port at the same time.
> 
> If one application listens on UDP443, another application can listen on TCP443.

tks

**Comment by Thaomtam** [comment]
> TCP port, 2 programmes cannot listen to the same port at the same time.
> 
> If one application listens on UDP443, another application can listen on TCP443.

![Screenshot_2023-11-04-07-02-39-557_com.vnp.myvinaphone.jpg](https://github.com/chika0801/sing-box-examples/assets/109426941/dbd13712-bb37-4e64-975f-29acc192eeff)

Dear Sir. Please give me an nginx configuration. I'm doing my certificate hacking. by singbox

**Comment by Thaomtam** [comment]
> TCP port, 2 programmes cannot listen to the same port at the same time.
> 
> If one application listens on UDP443, another application can listen on TCP443.

![Screenshot_2023-11-04-07-02-39-557_com.vnp.myvinaphone.jpg](https://github.com/chika0801/sing-box-examples/assets/109426941/dbd13712-bb37-4e64-975f-29acc192eeff)

Dear Sir. Please give me an nginx configuration. I'm doing my certificate hacking. by singbox

**Comment by chika0801** [comment]
I can't help you. Some basic usage is usually something you need to master on your own with self-study. It's all within the individual's own learning ability. I learnt the same way, and by asking AI and searching first if I didn't understand.

**Comment by Thaomtam** [comment]
> I can't help you. Some basic usage is usually something you need to master on your own with self-study. It's all within the individual's own learning ability. I learnt the same way, and by asking AI and searching first if I didn't understand.

Thank you. Once again, thank you sincerely. I've learned a lot from your github shares. You are my xray teacher

**Comment by chika0801** [comment]
I'm not an expert either, I'm also an entry level person.

**Comment by Thaomtam** [comment]
> I'm not an expert either, I'm also an entry level person.

yes sir
