### ISSUE TITLE
Help for ECH in sing-box

### ISSUE THREAD

**Issue by Gharib110** [chika0801/sing-box-examples#58]
Hello,
Can you help with ech in sing-box ? I have registered a domain in Cloudflare and have written a config with trojan-tcp with each enabled but when I check with Wireshark my sni is not concealed ?!!
Can you help me with this please ?
Best Regards

**Comment by chika0801** [comment]
Have you correctly added the relevant parameters that the sing-box documentation has about ECH in the appropriate places in the client and server configuration of Sing-box?

If yes. Then ECH it is enabled. As for how you use Wireshark to grab the client's network packets to determine that, I don't use that and I can't answer you.

Suggest you go to sing-box's github and ask a question or go to its telegram group.
