### ISSUE TITLE
sing-box-examples/Hysteria2 怎么实现端口跳跃

### ISSUE THREAD

**Issue by josbu** [chika0801/sing-box-examples#60]
sing-box-examples/Hysteria2 怎么实现端口跳跃

**Comment by chika0801** [comment]
应该是不能。如要用这功能两端或至少客户端用原版。建议你去sing-box的github发帖子咨询那边。

**Comment by yjd** [comment]
NekoBoxForAndroid 发了PR但是sing-box不接受。

**Comment by chika0801** [comment]
正常操作，作者可以不接受。
