### ISSUE TITLE
sing-box shadowTls ws +?

### ISSUE THREAD

**Issue by yjd** [chika0801/sing-box-examples#61]
你好，
ip已经无法直连，两端都使用sing-box，如标题需要配合哪一个协议才能走cloudflare中转。
用了 sing-box-examples/tree/main/ShadowTLS 测试才看到没有ws走不了cloudflare中转
以前用Trojan-go开ws就可以中转比较简单，不知道sing-box带的Trojan是否支持

**Comment by chika0801** [comment]
https://github.com/chika0801/sing-box-examples/tree/main/VMess-WebSocket

这个组合形式能用CF的CDN。坏处时假设你VPS的IP没被封0，就只会被封端口。

PS：建议你花钱再买一个VPS，用VLESS那一系列协议组合。

**Comment by yjd** [comment]
@chika0801 谢谢！
目前是想把这个被封的用cdn救一下，
明天试试 [VMess-WebSocket](https://github.com/chika0801/sing-box-examples/tree/main/VMess-WebSocket)
https://github.com/SagerNet/sing-box/issues/199 //这个倒是套了shadowTls但是看回复开了ws就用不了。
明天我一并测试，看看结果如何

**Comment by chika0801** [comment]
没见过（试过）shadowtls配 vmess 你的形式能通不通
