### ISSUE TITLE
IOS 的客户端，能给个配置示例吗？

### ISSUE THREAD

**Issue by lin1123** [chika0801/sing-box-examples#62]
安卓、windows的搓出来都能用，把安卓的配置文件导入到IOS就不行了，能给个示例吗？

**Comment by chika0801** [comment]
不能，我没ios不能试。听别人说，你把安卓的分应用代理那段删了试试，还不行，就改下tun模式有个参数现在是gxxxx的，你改成system试试。还的其它地方改不不知道了。
