### ISSUE TITLE
windows fakeIP的配置文件好像有点问题？

### ISSUE THREAD

**Issue by lin1123** [chika0801/sing-box-examples#63]
按照你的模板添加了这一行规则在路由规则中，测试dns泄露，测试结果全是国内的阿里dns，删除这一字段就是国外的dns了。
   {
        "outbound": "any",
        "server": "local"
      },

**Comment by lin1123** [comment]
"dns": {
    "servers": [
      {
        "tag": "Quad101",
        "address": "https://101.101.101.101/dns-query",
        "strategy": "prefer_ipv4",
        "detour": "🎯 全球直连"
      },
      {
        "tag": "alidns",
        "address": "https://223.6.6.6/dns-query",
        "strategy": "prefer_ipv4",
        "detour": "🎯 全球直连"
      },
      {
        "tag": "dns_block",
        "address": "rcode://success"
      },
      {
        "tag": "dns_fakeip",
        "address": "fakeip"
      }
    ],
    "rules": [
      {
        "geosite": "category-ads-all",
        "server": "dns_block",
        "disable_cache": true
      },
      {
        "outbound": "any",
        "server": "alidns"
      },
      {
        "geosite": [
          "cn",
          "private"
        ],
        "server": "alidns"
      },
      {
        "query_type": [
          "A",
          "AAAA"
        ],
        "server": "dns_fakeip"
      }
    ],
    "fakeip": {
      "enabled": true,
      "inet4_range": "198.18.0.0/15",
      "inet6_range": "fc00::/18"
    },
    "independent_cache": true,
    "strategy": "prefer_ipv4"
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "inet4_address": "172.19.0.1/30",
      "inet6_address": "fdfe:dcba:9876::1/126",
      "auto_route": true,
      "strict_route": true,
      "stack": "system",
      "sniff": true
    }
  ],
这是我之前的配置文件，会造成dns检测全是国内的

**Comment by chika0801** [comment]
我的模板去那些检测网站测结果是没漏。

你自己的配置，我不能帮你分析原因。

这参数如果你不了解它发挥的作用，在什么场景会被用到，建议你通常不写，也遇不到什么奇怪的问题。
