### ISSUE TITLE
update hysteria 2 server config

### ISSUE THREAD

**Issue by cbjn** [chika0801/sing-box-examples#65]
**masquerade**

HTTP3 server behavior when authentication fails.

**Comment by chika0801** [comment]
You can read its official documentation yourself, it's very detailed, I left this parameter out on purpose. My principle is that simple is good. And some personal opinions.

**Comment by chika0801** [comment]
Correction, in my initial reply to your official document I meant https://v2.hysteria.network/zh/docs/advanced/Full-Server-Config/

I now realise that you are asking how to use the masquerade field parameter in the sing-box configuration.

I can't help you, you can try it yourself. Or go to sing-box github or its telegram group for help.

**Comment by chika0801** [comment]
> Note: There is no evidence that any government or commercial firewalls are using "missing TCP HTTP/HTTPS" as a means of detecting Hysteria servers. This feature is only provided for users who want to "go the extra mile". And if so, there's no reason to listen on ports other than the default 80/443 (although Hysteria does allow it).


 This is on the hy document, a suggestion from the author. You may consider it.
