### ISSUE TITLE
请问作者，我客户端是如下配置，但是连不通

### ISSUE THREAD

**Issue by areyouokhaha** [chika0801/sing-box-examples#66]
为trojan grpc nginx padding协议，注，neokray可以用但是singbox客户端不可以。
以下是客户端config配置

  "outbounds": [
    {
      "type": "dns",
      "tag": "dns-out"
    },
    {
      "type": "direct",
      "tag": "direct-out"
    },
    {
      "type": "trojan",
      "tag": "trojan-grpc-padding",
      "server": "xx.xxx.xx",
      "server_port": 443,
      "password": "6xxbx-5xe-xxx-xxxxx-xxxx",
      "tls": {
        "enabled": true,
        "server_name": "xx.xxx.com"
      },
      "multiplex": {
        "enabled": true,
        "protocol": "h2mux",
        "max_connections": 8,
        "min_streams": 8,
        "padding": true
      },
      "transport": {
        "type": "grpc",
        "service_name": "xxxxx"
      }
    }
  ]

**Comment by chika0801** [comment]
nekoray我不用，你看下它能导出生成的配置文件不，如果能你就好参考下。
另外一点grpc就是复用，你再加mux系列参数也许并不会生效。

**Comment by areyouokhaha** [comment]
{
    "log": {
    "disabled": false,
    "level": "info",
    "timestamp": true
  },

  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "udp://8.8.8.8"
      }
    ]
  },



  "inbounds": [
{
      "type": "trojan",
      "tag": "trojan-grpc+TLS+CDN+Padding",
      "listen": "127.0.0.1",
      "listen_port": xxxx,
      "sniff": true,
      "sniff_override_destination": false,
      "users": [
        {
          "password": "xxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxxxxx"
       }
      ],

      "transport": {
        "type": "grpc",
        "service_name": "xxxxx"
      }
    }




  ],

    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ],
    "route": {
        "rules": [
{
                "protocol": "bittorrent",
                "outbound": "direct"
            }
        ]
    }

}
以上为服务端，另外删了mux也不行，neko的配置我下午时候导出来过，复制上去和参考了上面的参数，也不通，很奇怪，singbox客户端日志没有报过error

**Comment by areyouokhaha** [comment]
> 另外，这类不通提问通常建议你要发两端配置，别人才能可能帮到你。

老哥，谢谢了，自行解决了😂

**Comment by chika0801** [comment]
不用谢
