### ISSUE TITLE
ss与vm配置问题

### ISSUE THREAD

**Issue by wclmgcd** [chika0801/sing-box-examples#68]
由于clash删库，所以第一次试用sing-box，但是有两种节点配置不成功，官方的文档和大佬你的示例中都没有，都是机场的节点
1.ss    订阅是如下内容
- { name: CN丨Hongkong-04, type: ss, server: xxxxx.xxxxx, port: xxxxx, cipher: aes-256-gcm, password: 'xxxxxx', plugin: obfs, plugin-opts: { mode: http, host: xxxxxxxxxxx.microsoft.com }, udp: true }
在sing-box中，写成如下
{
        "type": "shadowsocks",
        "tag": "byw-hk01",
        "server": "xxxxx.xxxxx.com",
        "server_port": xxxxx,
        "method": "aes-256-gcm",
        "password": "xxxxxx",
        "plugin": "obfs-local",
        "plugin_opts": "mode: http, host: xxxxxxxx.microsoft.com"
    },

2.vmess-ws
 - { name: '🇯🇵 ①日本', type: vmess, server: xxxxxxxxx.xxxxxxx.cloud, port: xxxxx, uuid: xxxxxxxx-000-0000-0000-00000000, alterId: 0, cipher: auto, udp: true, network: ws, ws-opts: { path: /xxxxxx, headers: { Host: xx.xxxx.com } }, ws-path: /xxxxx, ws-headers: { Host: xx.xxxx.com } }
在sing-box改写如下
{
        "type": "vmess",
       "tag": "aky-jp01",
        "server": "xxxxxxxxx.xxxxxxx.cloud",
        "server_port": xxxxx,
        "uuid": "xxxxxxxx-000-0000-0000-00000000",
        "security": "auto",
        "alter_id": 0,
        "transport": {
            "type": "ws",
           "headers": {
              "Host": "xx.xxxx.com"
             },
            "path": "/xxxxxx"
        }
    }

，以上两种格式改写是那里不对，sing-box可以运行，但节点不能使用，测速也没有显示，希望大佬指点一下。

**Comment by wclmgcd** [comment]
还有一个config_client_android.json配置中，
{
                "type": "logical",
                "mode": "and",
                "rules": [
                    {
                        "geosite": [          //这里
                            "cn"
                        ]
                    },
                    {
                        "geoip": [          //这里  代表中国的域名和ip都已经是走直连了，下面为什么还有"geoip":  "cn"这这规则，
                            "cn"                 不会重复吗？ 
                        ]
                    }
                ],
                "outbound": "direct"
            },
            {
                "geosite": [
                    "private"                                                    //这里
                ],
                "outbound": "direct"
            },
            {
                "geoip": [
                    "cn",                                                        //这里
                    "private"
                ],
                "outbound": "direct"
            }

**Comment by chika0801** [comment]
建议自己学吧或去它的tg群问

**Comment by chika0801** [comment]
> 还有一个config_client_android.json配置中， { "type": "logical", "mode": "and", "rules": [ { "geosite": [ //这里 "cn" ] }, { "geoip": [ //这里 代表中国的域名和ip都已经是走直连了，下面为什么还有"geoip": "cn"这这规则， "cn" 不会重复吗？ ] } ], "outbound": "direct" }, { "geosite": [ "private" //这里 ], "outbound": "direct" }, { "geoip": [ "cn", //这里 "private" ], "outbound": "direct" }

逻辑是

1 域名在geosite cn中且IP在geoip cn中，走直连
2 那么就有域名在非geosite cn中，且IP在geoip cn中，走直连

大意是这样。
