### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ssd2077** [chika0801/sing-box-examples#71]
{
    "inbounds": [
        {
            "type": "socks",
            "listen": "127.0.0.1",
            "listen_port": 1080
        },
        {
            "type": "mixed",
            "listen": "::",
            "listen_port": 10000
        }
    ],
    "outbounds": [
        {
            "type": "vless",
            "tag": "vless-out",
            "server": "",
            "server_port": ,
            "uuid": "",
            "flow": "xtls-rprx-vision",
            "tls": {
                "enabled": true,
                "server_name": "",
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                },
                "reality": {
                    "enabled": true,
                    "public_key": "",
                    "short_id": ""
                }
            },
            "packet_encoding": "xudp"
        }
    ],
    "multiplex": {
        "enabled": true,
        "protocol": "h2mux",
        "max_connections": 1,
        "min_streams": 4,
        "padding": true,
        "brutal": {
            "enabled": true,
            "up_mbps": 50,
            "down_mbps": 1000
        }
    }
}客户端报错FATAL[0000] decode config at /root/sin-box.conf: json: unknown field "multiplex"

**Comment by ssd2077** [comment]
算了，用回bbr

**Comment by chika0801** [comment]
> 客户端报错FATAL[0000] decode config at /root/sin-box.conf: json: unknown field "multiplex"

使用最新测试版本的sing-box
