### ISSUE TITLE
Question regarding `dest` in sing-box

### ISSUE THREAD

**Issue by hawshemi** [chika0801/sing-box-examples#76]
In REALITY, we have 2 parameters, `serverName` and `dest`.
but in these sing-box templates, what is `dest`? is it automatically equal to `serverName`?

**Comment by chika0801** [comment]
An explanation of the parameters you can find in the xtls/reality repository.

Or see my xray configuration help repository.


For example, if you fill in the address abc com in the dest parameter, you can use your browser to see what domain names are included in the ssl certificate of this website, for example, 1.abc.com abc.com, and fill in the server name parameter with one of the domain names included in the ssl certificate.

**Comment by hawshemi** [comment]
Ow. I misspelled. Sorry.

I menat WHERE is `dest` parameter in singbox examples?

**Comment by chika0801** [comment]
`dest` https://github.com/chika0801/sing-box-examples/blob/b351d28e71d0a5d97ca0e90e686cd3b66546b2ce/VLESS-XTLS-uTLS-REALITY/config_server.json#L19

`serverName` https://github.com/chika0801/sing-box-examples/blob/b351d28e71d0a5d97ca0e90e686cd3b66546b2ce/VLESS-XTLS-uTLS-REALITY/config_server.json#L15

**Comment by hawshemi** [comment]
Thanks.
