### ISSUE TITLE
多路复用

### ISSUE THREAD

**Issue by ahhfzwl** [chika0801/sing-box-examples#81]
为什么客户端打开多路复用后有些节点就会失联？
所有服务器都是用VMess-WebSocket配置文件，只是修改port和uuid，其他参数均为改动。

**Comment by ahhfzwl** [comment]
我看这个配置文件没有多路复用的相关参数啊，怎么大部分节点都可以用呢，难道软件默认就是开启多路复用的？

**Comment by chika0801** [comment]
你要别人帮你，至少发一份你现在有问题的两端的配置，帮你看下有不有什么。你光这样说，也没用。

**Comment by ahhfzwl** [comment]
![Screenshot_2023-12-07-21-12-10-049_com server auditor ssh client-edit](https://github.com/chika0801/sing-box-examples/assets/54196143/656c287e-8cd2-4dff-8128-85d18b6903bb)
我在多台服务器上用的都是这个配置，节点在同一个客户端上使用，开启多路复用之后，有部分节点会失联。

**Comment by chika0801** [comment]
https://github.com/chika0801/sing-box-examples/blob/main/TCP_Burtal/config_server.json#L17

这段参数，是要两端都加，具体从哪一个版本开始这样的，你去看sing-box的更新日志就知道了。

所以你要用，两端core统一使用成一个版本，并且都加，才会有效。
```
            "multiplex": {
                "enabled": true,
                "padding": false,
                "brutal": {
                    "enabled": true,
                    "up_mbps": 100,
                    "down_mbps": 20
                }
            },
```

**Comment by chika0801** [comment]
两端加法，它文档也有写。上面配置是随便举的带TCP Burtal的例子。

**Comment by ahhfzwl** [comment]
> https://github.com/chika0801/sing-box-examples/blob/main/TCP_Burtal/config_server.json#L17
> 
> 这段参数，是要两端都加，具体从哪一个版本开始这样的，你去看sing-box的更新日志就知道了。
> 
> 所以你要用，两端core统一使用成一个版本，并且都加，才会有效。
> 
> ```
>             "multiplex": {
>                 "enabled": true,
>                 "padding": false,
>                 "brutal": {
>                     "enabled": true,
>                     "up_mbps": 100,
>                     "down_mbps": 20
>                 }
>             },
> ```

![Screenshot_2023-12-08-07-19-20-308_com android chrome](https://github.com/chika0801/sing-box-examples/assets/54196143/f4cadd03-a548-454b-adc6-3bed55b9630f)
还真是，从1.7版本开始默认不支持多路复用了，难怪有部分节点不行，现在回想一下，那些失联的节点都是最近搭建的，这下终于明白了，非常感谢。
