### ISSUE TITLE
VLESS-HTTP2-REALITY 此配置在1.8-rc2之后的版本会闪退

### ISSUE THREAD

**Issue by lin1123** [chika0801/sing-box-examples#85]
1.8-RC2之前的版本都能正常使用，升级到1.8-RC3及以后的版本全部闪退。因为RC3开始，http传输有改动。

**Comment by lin1123** [comment]
就因为这个在群里问了一句，直接送了我一张飞机票。。。。。。

**Comment by chika0801** [comment]
下回开小号去问，是个技巧。或者你在Xray群问不会被ban。

**Comment by chika0801** [comment]
另外 现在 VLESS TCP TLS 组合还不通了，不问不发ISS是好习惯。

**Comment by lin1123** [comment]
> 你只有等作者哪个版本可能自己就修好了。或者你去研究下配置，我也没空哪个版本都测试一遍。
> 
> 另外其实HTTP2和gRPC没区别，你换gRPC也行。
> 
> 或者我推销你用TCP Brutal也是更爽。

TCP Brutal虽然很爽，但是每个环境都要配置带宽有点麻烦。
感谢回复。

**Comment by chika0801** [comment]
```
            "transport": {
                "type": "http"
            }
```

刚测了一下，sing-box是刚自己编译的版本，然后有关配置就是上面这样写的，其实就是我现在的配置没变动。两端能连通。

TIP点是   `"host": ["www.example.com"]`   这个host参数，你两端都没写它，它是从v2ray继承的，其实是有 `www.example.com` 默认值。

所以 Xray和sing-box H2配置没写host都用这个host网址是互通的。IOS的小火箭就要手动写。 反正你自己排查好了。

**Comment by chika0801** [comment]
`TCP Brutal虽然很爽，但是每个环境都要配置带宽有点麻烦。`

这个我们测了跑不到高速，我最多120-150就冲不动了。你日常在服务端上行给100嘛，你客户端下也填100，真的够了。如果你不想开UDP类的如HY的话。我都在用它。

反正它和H2GRPC都是1个连接的复用所以我说没区别，用什么H2GRPC，TCPBRUTAL走起了

**Comment by chika0801** [comment]
另外，如果有什么，你还是来这发个ISS，我有空也试试看这儿不会BAN。有时在XRAY群发消息可能看不到。

**Comment by chika0801** [comment]
```
{
  "type": "http",
  "host": []
}
```

试了以最新版本为例
`"host": []` 这叫留空 
`"host": [""]` 这不叫留空。

服务端当留空或不写 "host": [] 时，客户端不写，或乱写 "host": [123] "host": ["123.cc"] 都能通，推测是服务端不会验证 "host": []

服务端写   "host": ["123.com"]

客户端必须一致才能通。

以前的版本是遵照v2fly历史，不写或留空值是 "host": ["www.example.com"]

他应该暗改了这些。试下就知道了。

**Comment by lin1123** [comment]
<img width="525" alt="屏幕截图 2023-12-28 180140" src="https://github.com/chika0801/sing-box-examples/assets/62827465/2a95d3ed-803c-4173-a68a-48b6a8971d46">
gan
感谢你的热心回复，我之前一直用的这样的配置。从RC3开始闪退了，已改回tcp传输层了。
顺便在提一句，您的shadowTLS的客户端配置，ss的出站没有加tag，是考虑到它是默认出站的原因吗？我在用clash api选择的时候，错误的选择的ss tls的出站。

**Comment by chika0801** [comment]
你图上现在的写法，我用最新源码测试是能通的。你再试试了。

**Comment by chika0801** [comment]
https://github.com/chika0801/sing-box-examples/blob/main/ShadowTLS/config_client.json#L11

它是出站第1个位置，是默认值。

https://github.com/chika0801/sing-box-examples/blob/main/ShadowTLS/config_client.json#L12

它用了detour（链式代理）发给了shadowtls协议了。

**Comment by chika0801** [comment]
我不用（不会）clash api，不清楚。
