### ISSUE TITLE
路由里面没有geosite-cn:direct规则？

### ISSUE THREAD

**Issue by shallbytwo** [chika0801/sing-box-examples#90]
我看路由里面只有geoip-cn：direct。为什么没有geosite-cn：direct呢？而且final还是走的proxy。
这样国内域名不都走proxy了吗？

**Comment by chika0801** [comment]
> 我看路由里面只有geoip-cn：direct。为什么没有geosite-cn：direct呢？而且final还是走的proxy。 这样国内域名不都走proxy了吗？

因为在tun模式下，进路由部分判断的条件有域名和ip 2个。

当ip是cn的请求就直连，剩下送代理。只需要通过ip是不是cn的就行了。

你可以想下假设geosite cn里有个域名现在ip是在国外，你用了，就成你本地直连这国外ip。

玩法很多，示例也只是个人爱好的用法。

**Comment by shallbytwo** [comment]
> > 我看路由里面只有geoip-cn：direct。为什么没有geosite-cn：direct呢？而且final还是走的proxy。 这样国内域名不都走proxy了吗？
> 
> 因为在tun模式下，进路由部分判断的条件有域名和ip 2个。
> 
> 当ip是cn的请求就直连，剩下送代理。只需要通过ip是不是cn的就行了。
> 
> 你可以想下假设geosite cn里有个域名现在ip是在国外，你用了，就成你本地直连这国外ip。
> 
> 玩法很多，示例也只是个人爱好的用法。

可是我实测weibo.com走了代理

**Comment by chika0801** [comment]
你这样问我也帮不上你。

你自己开日志trace，访问这网站，看它日志显示的流程，来一步步排查。
