### ISSUE TITLE
生成问题

### ISSUE THREAD

**Issue by Qvisl9** [chika0801/sing-box-examples#92]
现在reality生成uuid和reality-keypair已经不能用sing-box generate uuid了，是该如何生成uuid？

**Comment by chika0801** [comment]
你意思是sing-box 改了生成命令？

你自己看看sing-box 帮助怎么写的了。我好久没看了。

你可以用xray的命令来生成也是一样的。

**Comment by chika0801** [comment]
哦理解错了，以为你问reality的公私钥。

uuid 你随便输入 abc ,xray那边也用 abc 都能通，有个应射算法，sing-box文档中没提。

这算法好像我发现只在tuic中的uuid不行。其它地方是行的。

或者你找网页生成uuid方法多的是。
