### ISSUE TITLE
麻烦问一下关于geosite-localtion-!cn和geosite-cn的区别

### ISSUE THREAD

**Issue by kls1991** [chika0801/sing-box-examples#93]
请问这俩是完全互补的吗？比如一个域名，没命中geosite-cn的话，一定会命中geosite-location-!cn吗

如果是的话，为啥貌似大家都更喜欢geosite-location-!cn呢，明明这个名字更长啊

不好意思问这么细节的问题，主要是sing-box太戳我了...... 所以想对自己的配置尽可能了解

**Comment by chika0801** [comment]
https://github.com/xmdhs/sing-geosite/tree/rule-set

我记得这个是sing-box官方用的Fork后，显示了json内容，你自己看一下

另外一个有名的geo数据库是我们称加强版的，这人也有做
https://github.com/xmdhs/sing-geosite/tree/rule-set-Loyalsoldier

加强版你去看原作者关于geosite相比v2fly原版增加了哪些内容的介绍

等于说geosite原版是v2fly的，用得多的是-Loyalsoldier 的加强版
sing-box官方我认为是fork至v2fly版的Geosite

然后就是不建议你在服务端用加强版的geosite cn 分类阻止的行为，除非 你认真看懂了加强版的说明。

当然客户端你要用加强版的Geosite cn直连，你也要对加强版的说明有自己的了解 。

**Comment by chika0801** [comment]
另外 clash系那边有名的BM7，也有适配sing-box的版本在这

https://github.com/MetaCubeX/meta-rules-dat/tree/sing/bm7

至于我不熟悉bm7因为我不用Clash系
