### ISSUE TITLE
配置选择问题

### ISSUE THREAD

**Issue by tuki-code** [chika0801/sing-box-examples#96]
请教一下，在自己有域名且不需要过 CDN 的情况下，应当选择 VLESS-gRPC-TLS（将 nginx 前置）还是 VLESS-gRPC-REALITY（偷自己）？这两者在性能和安全性上有没有什么差别？

**Comment by chika0801** [comment]
两个组合方式，服务端的tls指纹，都是nginx的

区别是带有reality的组合，由于reality的要求，客户在的uTLS是要求必选。另外个就是可选。

还有个区别是你在sing-box用偷自己时，nginx的日志里不能记录正常访问你网站者的ip。是因为sing-box取消了那个叫proxy xxxx 功能的支持。当然这功能也不重要就是了。

速度上，nginx监听443的方案，你看里面加了些和grpc有关的参数，都是当时测试时群友研究出来的。

另外种你不需要懂这些。

最后玄学的断流现象，我没对比研究过。

你知道用grpc对vps要求是好线路这个条件吧。
