### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by msshn** [chika0801/sing-box-examples#98]
I want to know your opinion on `padding` setting under `mux` in sing-box. as written in sing-box documentation, it defaults to `padding: false` when not written, which is the case in your examples. isn't it a good idea to enable `padding: true` as it may enhance security?

Great examples BTW.

**Comment by chika0801** [comment]
In Chinese proxy translation circles (such as in telegram's group), my view is that the firewall detection behaviour of the TLS in TLS feature that exists in the opposite legend. In addition to VISION has a counteracting effect. Now there is also a more general view that http2 multiplexing can buffer attenuate it.

The padding parameter introduced in the sing-box configuration at the same time as h2mux (I was under the impression that they were added in the same release, so I can't guarantee that my memory is correct) The author of sing-box, from what I've seen, doesn't talk about this padding parameter in its telegram group as well. As I don't know GO code and expertise in this area either.

So with the known assumption that TLS in TLS is valid with h2mux. Whether using padding again at the same time is reinforcing or counterproductive, I don't know.

**Comment by chika0801** [comment]
If you need further advice, I suggest you go to sing-box's github and ask the author a question.

**Comment by chika0801** [comment]
Sometimes write examples, just in the spirit of the simplest principle, so I see sing-box documentation did not write more other parameters, and there is no special meaning.
